DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS logs;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(128) UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  details TEXT NOT NULL,
  timestamp DATETIME NOT NULL
)
